DROP TABLE MEMBER;
DROP TABLE POST;
DROP TABLE COMMENT;

CREATE TABLE MEMBER
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NICKNAME      VARCHAR    NOT NULL UNIQUE,
    LOGIN_ID      VARCHAR    NOT NULL UNIQUE,
    PASSWORD      VARCHAR    NOT NULL,
    REGISTER_DATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS        VARCHAR NOT NULL DEFAULT 'USING'
);

CREATE TABLE POST
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE         VARCHAR    NOT NULL,
    CONTENT       VARCHAR    NOT NULL,
    REGISTER_DATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY_DATE   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS        VARCHAR NOT NULL DEFAULT 'USING',
    VIEWS         INT DEFAULT 0,
    MEMBER_ID     BIGINT     NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE
);

CREATE TABLE COMMENT
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    CONTENT       VARCHAR    NOT NULL,
    REGISTER_DATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY_DATE   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS        VARCHAR NOT NULL DEFAULT 'USING',
    SCORE         INT NOT NULL,
    MEMBER_ID     BIGINT     NOT NULL,
    POST_ID       BIGINT     NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST (ID) ON DELETE CASCADE
)
;