CREATE TABLE MEMBER
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NICKNAME      VARCHAR    NOT NULL UNIQUE,
    LOGIN_ID      VARCHAR    NOT NULL UNIQUE,
    PASSWORD      VARCHAR    NOT NULL,
    REGISTER_DATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS        VARCHAR(1) NOT NULL DEFAULT '0'
);

CREATE TABLE POST
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE         VARCHAR    NOT NULL,
    CONTENT       VARCHAR    NOT NULL,
    REGISTER_DATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY_DATE   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS        VARCHAR NOT NULL DEFAULT '0',
    MEMBER_ID     BIGINT     NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE
);

CREATE TABLE COMMENT
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    CONTENT       VARCHAR    NOT NULL,
    REGISTER_DATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY_DATE   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS        VARCHAR(1) NOT NULL DEFAULT '0',
    SCORE         INT,
    MEMBER_ID     BIGINT     NOT NULL,
    POST_ID       BIGINT     NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST (ID) ON DELETE CASCADE
)
;